# Generated by Django 4.2.8 on 2023-12-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/announcements')),
                ('title', models.CharField(max_length=255)),
                ('ilmiy_rahbari', models.CharField(max_length=50)),
                ('ilmiy_rahbari_email', models.EmailField(max_length=254)),
                ('ilmiy_hamrahbari', models.CharField(max_length=50)),
                ('ilmiy_hamrahbari_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('full_name', models.CharField(max_length=255)),
                ('yonalish', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('xodimlar_soni', models.IntegerField()),
                ('bolim_maqsadi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('view', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('full_name', models.CharField(max_length=255)),
                ('yonalish', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('ish_vaqti', models.CharField(max_length=255)),
                ('biografiya', models.CharField(max_length=255)),
                ('talim', models.CharField(max_length=255)),
                ('unvon', models.CharField(max_length=100)),
                ('kasbiy_faoliyati', models.CharField(max_length=400)),
                ('mukofotlar', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='apps.news')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
                ('maintxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='apps.announcements')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('maintxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_email', to='apps.announcements')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_txt', models.TextField()),
                ('maintxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_documents', to='apps.announcements')),
            ],
        ),
    ]
