# Generated by Django 4.2.8 on 2023-12-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_scientificcouncil_photogallery_user_academicdegree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdegree',
            old_name='academicdegree',
            new_name='academic_degree',
        ),
    ]
