# Generated by Django 4.2.8 on 2023-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_academicdegree_academicdegree_academic_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='user',
        ),
        migrations.AddField(
            model_name='scientificcouncil',
            name='academic_degree',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AcademicDegree',
        ),
    ]
