# Generated by Django 4.2.8 on 2023-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_photogallery_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
