# Generated by Django 4.2.8 on 2023-12-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_videogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='title',
        ),
    ]
